### ISSUE TITLE
Vector class design

### ISSUE THREAD

**Issue by pelson** [marqh/vectorfield#1]
A few observations:
- I'm uncertain if there is a canonical for to store vector data in - it could be x and y component magnitudes (Cartesian) or magnitude and direction (polar) in 2D - and even more general in higher dimensions.
- Numerically it is often convenient compute and store winds on staggered grids, but the staggering depends on the scheme in question - are each of the staggering possibilities a subclass, or are they just handled in the `__init__` and stored in some canonical form? i.e. Is there ever a case where you would want to specialize a method of a `VectorField` to do some optimized thing on your own type of staggering (such as for visualisation or some analysis)

Looks interesting though. Thanks for sharing.

**Comment by marqh** [comment]
> I'm uncertain if there is a canonical for to store vector data in - it could be x and y component magnitudes (Cartesian) or magnitude and direction (polar) in 2D - and even more general in higher dimensions.

My thought process to date is based on my assumption that all components should be able to be stored, I have seen data sets where i and j components are recorded, as is magnitude, as this is derived by some modelling process using a specific algorithm.  I think this should be handled, I do not think it is simply over-specification.

Where a component is not explicitly stored, a method may be provided to derive an answer depending on the available components. A particular implementation may choose to create a sub-class to adapt this behaviour for particular tasks

**Comment by marqh** [comment]
> Numerically it is often convenient compute and store winds on staggered grids, but the staggering depends on the scheme in question - are each of the staggering possibilities a subclass, or are they just handled in the **init** and stored in some canonical form? i.e. Is there ever a case where you would want to specialize a method of a VectorField to do some optimized thing on your own type of staggering (such as for visualisation or some analysis)

I think that the variety of staggered grids may be able to be handled by one class.  The key factor for me is the ability to colocate components to enable operations to be conducted safely.

As long as some behaviour is made available to co-locate components, then I think the behaviour is pretty generic.
